import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    backgroundColor: '#0b1724',
    flex: 1,
  },
  appBackground: {
    backgroundColor: '#08111f',
    flex: 1,
  },
  workspace: {
    flex: 1,
    flexDirection: 'row',
    gap: 16,
    paddingBottom: 16,
    paddingHorizontal: 16,
  },
  mainSurface: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    overflow: 'hidden',
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 16,
    minHeight: 78,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  brandLockup: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minWidth: 230,
  },
  searchBox: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  searchText: {
    color: '#8fa3b8',
    fontSize: 13,
    fontWeight: '700',
  },
  topActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  rolePicker: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  rolePill: {
    alignItems: 'center',
    borderRadius: 6,
    justifyContent: 'center',
    minHeight: 30,
    paddingHorizontal: 9,
  },
  rolePillActive: {
    backgroundColor: '#f4f8fb',
  },
  rolePillText: {
    color: '#b5c4d4',
    fontSize: 10,
    fontWeight: '900',
  },
  rolePillTextActive: {
    color: '#102337',
  },
  sidebar: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
    width: 238,
  },
  sidebarLabel: {
    color: '#7f94aa',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  sidebarItem: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    minHeight: 44,
    paddingHorizontal: 11,
  },
  sidebarItemActive: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
  },
  sidebarGlyph: {
    color: '#7f94aa',
    fontSize: 15,
    fontWeight: '900',
    width: 18,
  },
  sidebarGlyphActive: {
    color: '#ffffff',
  },
  sidebarText: {
    color: '#a9b8c8',
    fontSize: 13,
    fontWeight: '800',
  },
  sidebarTextActive: {
    color: '#ffffff',
  },
  mobileNavShell: {
    backgroundColor: '#0b1724',
    borderTopColor: 'rgba(255,255,255,0.12)',
    borderTopWidth: 1,
    paddingBottom: 8,
    paddingTop: 8,
  },
  mobileNavContent: {
    gap: 8,
    paddingHorizontal: 10,
  },
  mobileNavItem: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.10)',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 54,
    minWidth: 96,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  mobileNavItemActive: {
    backgroundColor: '#f4f8fb',
  },
  mobileNavGlyph: {
    color: '#a9b8c8',
    fontSize: 14,
    fontWeight: '900',
  },
  mobileNavGlyphActive: {
    color: '#102337',
  },
  mobileNavText: {
    color: '#a9b8c8',
    fontSize: 10,
    fontWeight: '800',
    marginTop: 4,
  },
  mobileNavTextActive: {
    color: '#102337',
  },
  glassCard: {
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderColor: 'rgba(255,255,255,0.72)',
    borderRadius: 8,
    borderWidth: 1,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.14,
    shadowRadius: 28,
  },
  metricCard: {
    flex: 1,
    minHeight: 136,
    minWidth: 210,
    overflow: 'hidden',
    padding: 18,
  },
  metricAccent: {
    height: 3,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  metricCardLabel: {
    color: '#526579',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 14,
    textTransform: 'uppercase',
  },
  metricCardValue: {
    color: '#0f1f33',
    fontSize: 28,
    fontWeight: '900',
  },
  metricCardHelper: {
    color: '#63758a',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 8,
  },
  statusChip: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderRadius: 5,
    justifyContent: 'center',
    minHeight: 25,
    paddingHorizontal: 8,
  },
  statusChipText: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  statusChipBlue: {
    backgroundColor: '#e5efff',
  },
  statusChipGreen: {
    backgroundColor: '#ddf5ed',
  },
  statusChipAmber: {
    backgroundColor: '#fff2d5',
  },
  statusChipRed: {
    backgroundColor: '#ffe4e4',
  },
  statusChipNeutral: {
    backgroundColor: '#edf2f7',
  },
  statusChipTextBlue: {
    color: '#285fa9',
  },
  statusChipTextGreen: {
    color: '#19765f',
  },
  statusChipTextAmber: {
    color: '#8a5a00',
  },
  statusChipTextRed: {
    color: '#b42318',
  },
  statusChipTextNeutral: {
    color: '#5e7084',
  },
  page: {
    flex: 1,
    padding: 22,
  },
  pageHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  pageKicker: {
    color: '#93a6ba',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  pageTitle: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '900',
  },
  pageSubtitle: {
    color: '#b8c7d6',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 6,
    maxWidth: 720,
  },
  pageActions: {
    alignItems: 'flex-end',
    gap: 8,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  contentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  widePanel: {
    flex: 2,
    minWidth: 320,
    padding: 18,
  },
  sidePanel: {
    flex: 1,
    minWidth: 280,
    padding: 18,
  },
  panelTitle: {
    color: '#102337',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 12,
  },
  tableRow: {
    alignItems: 'center',
    borderTopColor: 'rgba(16,35,55,0.10)',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 58,
    paddingVertical: 10,
  },
  tablePrimary: {
    color: '#102337',
    fontSize: 13,
    fontWeight: '900',
  },
  tableSecondary: {
    color: '#62758a',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  tableAmount: {
    color: '#102337',
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  tableAction: {
    color: '#cc6b49',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 3,
    textAlign: 'right',
  },
  uploadFormGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  formColumn: {
    flex: 1,
    minWidth: 220,
  },
  uploadButtonDark: {
    alignItems: 'center',
    backgroundColor: '#102337',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 14,
  },
  uploadButtonDarkText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
  planGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  planCard: {
    backgroundColor: '#ffffff',
    borderColor: '#dce4ee',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minWidth: 220,
    padding: 14,
  },
  planCardActive: {
    borderColor: '#1f8a70',
    borderWidth: 2,
  },
  planBenefit: {
    color: '#45586d',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 8,
  },  uploadDropzone: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderColor: 'rgba(255,255,255,0.24)',
    borderRadius: 8,
    borderStyle: 'dashed',
    borderWidth: 1,
    minHeight: 238,
    justifyContent: 'center',
    marginBottom: 16,
    padding: 24,
  },
  uploadTitle: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 8,
  },
  uploadCopy: {
    color: '#b8c7d6',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
  },
  uploadButton: {
    backgroundColor: '#f4f8fb',
    borderRadius: 8,
    marginTop: 18,
    minHeight: 44,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  uploadButtonText: {
    color: '#102337',
    fontSize: 13,
    fontWeight: '900',
  },
  shell: {
    backgroundColor: '#f5f7fa',
    flex: 1,
  },
  header: {
    backgroundColor: '#0b1724',
    paddingBottom: 18,
    paddingHorizontal: 18,
    paddingTop: 14,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  logoFrame: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  logo: {
    height: 32,
    width: 32,
  },
  brand: {
    color: '#ffffff',
    fontSize: 23,
    fontWeight: '800',
  },
  headerSubline: {
    color: '#9db0c4',
    fontSize: 12,
    marginTop: 3,
  },
  segmented: {
    backgroundColor: '#15283b',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 5,
    padding: 5,
  },
  segment: {
    alignItems: 'center',
    borderRadius: 6,
    flex: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 4,
  },
  segmentActive: {
    backgroundColor: '#ffffff',
  },
  segmentText: {
    color: '#b8c6d5',
    fontSize: 11,
    fontWeight: '800',
  },
  segmentTextActive: {
    color: '#102337',
  },
  scroll: {
    flex: 1,
  },
  content: {
    padding: 18,
    paddingBottom: 22,
  },
  contentWide: {
    alignSelf: 'center',
    maxWidth: 980,
    width: '100%',
  },
  heroCard: {
    backgroundColor: '#102337',
    borderRadius: 8,
    marginBottom: 14,
    padding: 18,
  },
  heroTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  heroLabel: {
    color: '#b9c7d6',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  heroAmount: {
    color: '#ffffff',
    fontSize: 42,
    fontWeight: '900',
    marginTop: 8,
  },
  heroCaption: {
    color: '#d5dde7',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 5,
  },
  heroMetrics: {
    borderTopColor: '#29445d',
    borderTopWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
    marginTop: 20,
    paddingTop: 16,
  },
  metric: {
    minWidth: 130,
  },
  metricLabel: {
    color: '#8ba0b6',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0,
    marginBottom: 5,
    textTransform: 'uppercase',
  },
  metricValue: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  commandRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#cc6b49',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  primaryButtonCompact: {
    alignItems: 'center',
    backgroundColor: '#cc6b49',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 14,
    minHeight: 46,
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#d8dee6',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 18,
  },
  secondaryButtonText: {
    color: '#33485f',
    fontSize: 13,
    fontWeight: '800',
  },
  disabled: {
    opacity: 0.45,
  },
  panel: {
    backgroundColor: '#ffffff',
    borderColor: '#e1e6ee',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 16,
    padding: 16,
  },
  sectionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 4,
  },
  sectionRowCompact: {
    marginBottom: 8,
    marginTop: 0,
  },
  sectionTitle: {
    color: '#102337',
    flex: 1,
    fontSize: 19,
    fontWeight: '900',
  },
  sectionTitleCompact: {
    fontSize: 15,
  },
  sectionAction: {
    color: '#667789',
    fontSize: 11,
    fontWeight: '800',
    marginLeft: 10,
    textAlign: 'right',
    textTransform: 'uppercase',
  },
  factorGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 8,
  },
  factorCard: {
    backgroundColor: '#ffffff',
    borderColor: '#e1e6ee',
    borderRadius: 8,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    minHeight: 104,
    padding: 14,
  },
  factorLabel: {
    color: '#26394d',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
    marginTop: 14,
  },
  workflowRow: {
    flexDirection: 'row',
    minHeight: 48,
  },
  workflowRail: {
    alignItems: 'center',
    width: 24,
  },
  workflowDot: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#cbd5e1',
    borderRadius: 8,
    borderWidth: 2,
    height: 16,
    justifyContent: 'center',
    width: 16,
  },
  workflowDotActive: {
    backgroundColor: '#fff0e9',
    borderColor: '#cc6b49',
  },
  workflowDotDone: {
    backgroundColor: '#1f8a70',
    borderColor: '#1f8a70',
  },
  workflowCheck: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
    lineHeight: 12,
  },
  workflowLine: {
    backgroundColor: '#dde5ee',
    flex: 1,
    width: 2,
  },
  workflowLineDone: {
    backgroundColor: '#69b59f',
  },
  workflowCopy: {
    flex: 1,
    paddingLeft: 10,
  },
  workflowLabel: {
    color: '#6e7f91',
    fontSize: 13,
    fontWeight: '700',
  },
  workflowLabelActive: {
    color: '#102337',
    fontWeight: '900',
  },
  workflowMeta: {
    color: '#8a99a8',
    fontSize: 11,
    marginTop: 3,
  },
  invoiceCard: {
    backgroundColor: '#ffffff',
    borderColor: '#e1e6ee',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 16,
    padding: 16,
  },
  invoiceHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  invoiceTitleGroup: {
    flex: 1,
  },
  invoiceNumber: {
    color: '#102337',
    fontSize: 17,
    fontWeight: '900',
  },
  invoiceBuyer: {
    color: '#667789',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  amountBand: {
    backgroundColor: '#eef4f8',
    borderRadius: 8,
    marginBottom: 10,
    marginTop: 16,
    padding: 14,
  },
  amountLabel: {
    color: '#647588',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  amountValue: {
    color: '#102337',
    fontSize: 30,
    fontWeight: '900',
    marginTop: 6,
  },
  infoRow: {
    alignItems: 'center',
    borderTopColor: '#edf1f5',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 44,
    paddingVertical: 9,
  },
  infoLabel: {
    color: '#718195',
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
  },
  infoValue: {
    color: '#102337',
    flex: 1.15,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'right',
  },
  checkRow: {
    alignItems: 'center',
    borderTopColor: '#edf1f5',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 46,
    paddingVertical: 9,
  },
  checkMark: {
    alignItems: 'center',
    backgroundColor: '#eef2f6',
    borderRadius: 7,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  checkMarkActive: {
    backgroundColor: '#dff5ee',
  },
  checkSymbol: {
    color: '#8a99a8',
    fontSize: 13,
    fontWeight: '900',
  },
  checkSymbolActive: {
    color: '#1f8a70',
  },
  checkLabel: {
    color: '#26394d',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
  },
  checkValue: {
    color: '#6b7c8f',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'right',
  },
  scoreRow: {
    alignItems: 'center',
    borderTopColor: '#edf1f5',
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingVertical: 9,
  },
  scoreLabel: {
    color: '#26394d',
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    paddingRight: 12,
  },
  fundingPanel: {
    alignItems: 'center',
    backgroundColor: '#102337',
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    padding: 18,
  },
  fundingCopy: {
    flex: 1,
    paddingRight: 12,
  },
  smallCaps: {
    color: '#9fb0c2',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  fundingAmount: {
    color: '#ffffff',
    fontSize: 34,
    fontWeight: '900',
    marginTop: 8,
  },
  fundingCaption: {
    color: '#c4d0dc',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 3,
  },
  stepper: {
    flexDirection: 'row',
    gap: 8,
  },
  stepperButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  stepperText: {
    color: '#102337',
    fontSize: 22,
    fontWeight: '900',
  },
  lockedText: {
    color: '#45586d',
    fontSize: 13,
    lineHeight: 20,
    marginTop: 12,
  },
  offerCard: {
    backgroundColor: '#ffffff',
    borderColor: '#e1e6ee',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 12,
    padding: 16,
  },
  offerCardAccepted: {
    borderColor: '#1f8a70',
    borderWidth: 2,
  },
  cardMuted: {
    opacity: 0.58,
  },
  offerTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  offerCopy: {
    flex: 1,
  },
  offerTitle: {
    color: '#102337',
    fontSize: 16,
    fontWeight: '900',
  },
  offerPartner: {
    color: '#667789',
    fontSize: 12,
    marginTop: 4,
  },
  offerBadges: {
    alignItems: 'flex-end',
    gap: 6,
  },
  offerStats: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  miniStat: {
    backgroundColor: '#f3f6f9',
    borderRadius: 8,
    flex: 1,
    minHeight: 70,
    padding: 10,
  },
  miniStatLabel: {
    color: '#718195',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  miniStatValue: {
    color: '#102337',
    fontSize: 13,
    fontWeight: '900',
  },
  offerButton: {
    alignItems: 'center',
    backgroundColor: '#1f8a70',
    borderRadius: 8,
    justifyContent: 'center',
    marginTop: 14,
    minHeight: 44,
  },
  offerButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
  auditRow: {
    alignItems: 'flex-start',
    borderTopColor: '#edf1f5',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 12,
  },
  auditDot: {
    backgroundColor: '#cbd5e1',
    borderRadius: 5,
    height: 10,
    marginTop: 4,
    width: 10,
  },
  auditDotActive: {
    backgroundColor: '#1f8a70',
  },
  auditText: {
    color: '#26394d',
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
  },
  ruleRow: {
    borderTopColor: '#edf1f5',
    borderTopWidth: 1,
    paddingVertical: 12,
  },
  ruleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  ruleLabel: {
    color: '#26394d',
    fontSize: 13,
    fontWeight: '800',
  },
  ruleValue: {
    color: '#667789',
    fontSize: 12,
    fontWeight: '800',
  },
  ruleTrack: {
    backgroundColor: '#e4eaf1',
    borderRadius: 5,
    height: 8,
    overflow: 'hidden',
  },
  ruleFill: {
    backgroundColor: '#326fbd',
    borderRadius: 5,
    height: 8,
  },
  modelHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  modelTitle: {
    color: '#102337',
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 8,
  },
  modelCopy: {
    color: '#45586d',
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 12,
  },
  taskList: {
    gap: 10,
    marginBottom: 16,
  },
  taskCard: {
    backgroundColor: '#ffffff',
    borderColor: '#e1e6ee',
    borderRadius: 8,
    borderWidth: 1,
    padding: 14,
  },
  taskCardActive: {
    borderColor: '#326fbd',
    borderWidth: 2,
  },
  taskCardTop: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginBottom: 9,
  },
  taskName: {
    color: '#102337',
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
  },
  taskMap: {
    color: '#667789',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  badge: {
    alignSelf: 'flex-start',
    borderRadius: 5,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  badgeBlue: {
    backgroundColor: '#e6f0ff',
  },
  badgeGreen: {
    backgroundColor: '#ddf5ed',
  },
  badgeAmber: {
    backgroundColor: '#fff2d5',
  },
  badgeRed: {
    backgroundColor: '#ffe4e4',
  },
  badgeSlate: {
    backgroundColor: '#e6edf5',
  },
  badgeNeutral: {
    backgroundColor: '#eef2f6',
  },
  badgeTextBlue: {
    color: '#326fbd',
  },
  badgeTextGreen: {
    color: '#19765f',
  },
  badgeTextAmber: {
    color: '#9a6200',
  },
  badgeTextRed: {
    color: '#b42318',
  },
  badgeTextSlate: {
    color: '#40556b',
  },
  badgeTextNeutral: {
    color: '#667789',
  },
  tabBar: {
    backgroundColor: '#ffffff',
    borderTopColor: '#dfe6ee',
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingBottom: 8,
    paddingHorizontal: 8,
    paddingTop: 9,
  },
  tabButton: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    gap: 4,
    minHeight: 54,
    paddingVertical: 6,
  },
  tabButtonActive: {
    backgroundColor: '#eef4f8',
  },
  tabSymbol: {
    color: '#8a99a8',
    fontSize: 15,
    fontWeight: '900',
  },
  tabSymbolActive: {
    color: '#102337',
  },
  tabText: {
    color: '#75869a',
    fontSize: 10,
    fontWeight: '800',
  },
  tabTextActive: {
    color: '#102337',
  },
  accountName: {
    color: '#d8e2ee',
    fontSize: 12,
    fontWeight: '800',
    maxWidth: 180,
  },
  signOutButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.10)',
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 34,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  signOutText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
  },
  appError: {
    backgroundColor: '#ffe4e4',
    borderRadius: 8,
    color: '#b42318',
    fontSize: 12,
    fontWeight: '800',
    marginHorizontal: 22,
    marginTop: 16,
    padding: 12,
  },
  appNotice: {
    backgroundColor: '#e5efff',
    borderRadius: 8,
    color: '#285fa9',
    fontSize: 12,
    fontWeight: '800',
    marginHorizontal: 22,
    marginTop: 16,
    padding: 12,
  },
  authShell: {
    alignItems: 'center',
    backgroundColor: '#08111f',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  authPanel: {
    backgroundColor: 'rgba(255,255,255,0.90)',
    borderColor: 'rgba(255,255,255,0.72)',
    borderRadius: 8,
    borderWidth: 1,
    maxWidth: 520,
    padding: 22,
    width: '100%',
  },
  loadingCard: {
    backgroundColor: 'rgba(255,255,255,0.90)',
    borderRadius: 8,
    padding: 22,
  },
  authTitle: {
    color: '#102337',
    fontSize: 28,
    fontWeight: '900',
    marginBottom: 8,
  },
  authCopy: {
    color: '#526579',
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 20,
    marginBottom: 18,
  },
  fieldLabel: {
    color: '#40556b',
    fontSize: 11,
    fontWeight: '900',
    marginBottom: 7,
    marginTop: 10,
    textTransform: 'uppercase',
  },
  textInput: {
    backgroundColor: '#ffffff',
    borderColor: '#cfd9e5',
    borderRadius: 8,
    borderWidth: 1,
    color: '#102337',
    fontSize: 14,
    fontWeight: '700',
    minHeight: 46,
    paddingHorizontal: 12,
  },
  accountTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  accountTypeButton: {
    alignItems: 'center',
    backgroundColor: '#eef2f6',
    borderColor: '#d8e0ea',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 40,
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  accountTypeButtonActive: {
    backgroundColor: '#102337',
    borderColor: '#102337',
  },
  accountTypeText: {
    color: '#40556b',
    fontSize: 12,
    fontWeight: '900',
  },
  accountTypeTextActive: {
    color: '#ffffff',
  },
  authError: {
    backgroundColor: '#ffe4e4',
    borderRadius: 8,
    color: '#b42318',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
    marginTop: 14,
    padding: 10,
  },
  authNotice: {
    backgroundColor: '#ddf5ed',
    borderRadius: 8,
    color: '#19765f',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
    marginTop: 14,
    padding: 10,
  },  authSwitch: {
    alignItems: 'center',
    marginTop: 12,
    minHeight: 40,
    justifyContent: 'center',
  },});
